" Dvorak Remappings
noremap k t
noremap K T
noremap t <DOWN>
noremap n <UP>
noremap h <LEFT>
noremap s <RIGHT>
noremap T 10<DOWN>
noremap N 10<UP>
noremap H 10<LEFT>
noremap S 10<RIGHT>
noremap b n
noremap B N
